I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/intro2.rpy", line 3, in script
    label intro2:
Exception: Could not find return label ('game/intro1.rpy', 1668398102, 357).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/intro2.rpy", line 3, in script
    label intro2:
  File "C:\Users\samma\Downloads\renpy-8.0.2-sdk\renpy\ast.py", line 1782, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "C:\Users\samma\Downloads\renpy-8.0.2-sdk\renpy\execution.py", line 726, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label ('game/intro1.rpy', 1668398102, 357).

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.2.22081402
Planetary Pursuits ver.0.2
Thu May  4 22:32:29 2023
