I'm sorry, but an uncaught exception occurred.

Compiling ATL code at game/pluto_date2b.rpy:185
  File "game/script.rpy", line 34, in script call
    call pluto_date2b
  File "game/pluto_date2b.rpy", line 181, in script
    scene bg cabin room with dissolve:
  File "game/pluto_date2b.rpy", line 185, in <module>
    pause1
NameError: name 'pause1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 34, in script call
    call pluto_date2b
  File "game/pluto_date2b.rpy", line 181, in script
    scene bg cabin room with dissolve:
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\ast.py", line 1542, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\exports.py", line 712, in show
    sls.add(layer, img, key, zorder, behind, at_list=at_list, name=name, atl=atl, default_transform=default_transform, transient=transient)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\core.py", line 1165, in add
    thing.visit_all(lambda d : None)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\core.py", line 572, in visit_all
    for d in self.visit():
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\atl.py", line 614, in visit
    block = self.compile()
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\atl.py", line 521, in compile
    block = self.atl.compile(self.context)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\atl.py", line 721, in compile
    statements = [ i.compile(ctx) for i in self.statements ]
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\atl.py", line 721, in <listcomp>
    statements = [ i.compile(ctx) for i in self.statements ]
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\atl.py", line 969, in compile
    child = ctx.eval(expr)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\atl.py", line 259, in eval
    return renpy.python.py_eval(expr, locals=self.context)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/pluto_date2b.rpy", line 185, in <module>
    pause1
NameError: name 'pause1' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Planetary Pursuits ver.0.2
Thu May  4 00:05:40 2023
